packages:
  remote_package_files:
    url: https://github.com/masterd89/esphome_radar_pir
    files: 
      - path: esphome_config.yaml  # optional; if not specified, all files will be included
    
    refresh: 1min

dashboard_import:
  package_import_url: github://masterd89/esphome_radar_pir/esphome_main.yaml
  import_full_config: false 

